release:
	javac -d build Players/Player.java Players/IA.java Players/Human.java Management/Grid.java Management/Round.java Features/Display.java Features/Errors.java Features/History.java Features/Scan.java
run:
	java -cp build Main.java
run_jar: 
	java -jar puissance.jar
